/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doacao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class GUIDoacao extends javax.swing.JFrame {

    public GUIDoacao() {
        initComponents();
        setVisible(true);
    }

    public void addListener(GerenciadorDoacao gd) {
        JBTcadastrar.addActionListener(gd);
        JBTdeletar.addActionListener(gd);
        JBTconsultar.addActionListener(gd);
    }

    public Doacao getDoacao() {
        Doacao d = new Doacao();
        d.setIddoacao(Integer.parseInt(JTFiddoacao.getText()));
        d.setIdvoluntario(Integer.parseInt(JTFidvoluntario.getText()));
        d.setIdescola(Integer.parseInt(JTFidescola.getText()));
        d.setIdproduto(Integer.parseInt(JTFidproduto.getText()));
        d.setData(dataDoacao());
        return d;
    }
    
    public String dataDoacao(){
        String datadoacao;
        
        datadoacao = JTFdoaano.getText() + "-" + JTFdoames.getText() + "-" + JTFdoadia.getText();
        
        return datadoacao;
    }
    
    public int getID(){
        return Integer.parseInt(JTFiddoacao.getText());
    }

    public void limpar(){
        JTFiddoacao.setText("");
        JTFidvoluntario.setText("");
        JTFidescola.setText("");
        JTFidproduto.setText("");
        JTFdoaano.setText("");
        JTFdoames.setText("");
        JTFdoadia.setText("");
    }
    
    public void consultar() {
        try {
            DAODoacao objdoacaodao = new DAODoacao();
            DefaultTableModel model = (DefaultTableModel) JTBdoacao.getModel();
            ArrayList<Doacao> lista = objdoacaodao.Display();
            model.setRowCount(0);
            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getIddoacao(),
                    lista.get(num).getIdvoluntario(),
                    lista.get(num).getIdescola(),
                    lista.get(num).getIdproduto(),
                    lista.get(num).getData()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTcadastrar = new javax.swing.JButton();
        JBTdeletar = new javax.swing.JButton();
        JLescola = new javax.swing.JLabel();
        JLtitulo = new javax.swing.JLabel();
        JTFidescola = new javax.swing.JTextField();
        JLiddoacao = new javax.swing.JLabel();
        JBTconsultar = new javax.swing.JButton();
        JLvoluntario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTBdoacao = new javax.swing.JTable();
        JTFidproduto = new javax.swing.JTextField();
        JTFidvoluntario = new javax.swing.JTextField();
        JTFdoaano = new javax.swing.JTextField();
        JLdatadoacao = new javax.swing.JLabel();
        JTFdoames = new javax.swing.JTextField();
        JTFdoadia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        JLiddoacao1 = new javax.swing.JLabel();
        JTFiddoacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doação");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        JBTcadastrar.setBackground(new java.awt.Color(247, 255, 247));
        JBTcadastrar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JBTcadastrar.setForeground(new java.awt.Color(102, 0, 102));
        JBTcadastrar.setText("Cadastrar");
        JBTcadastrar.setName("cadastrar"); // NOI18N
        JBTcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrarActionPerformed(evt);
            }
        });

        JBTdeletar.setBackground(new java.awt.Color(247, 255, 247));
        JBTdeletar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JBTdeletar.setForeground(new java.awt.Color(102, 0, 102));
        JBTdeletar.setText("Deletar");
        JBTdeletar.setName("deletar"); // NOI18N
        JBTdeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTdeletarActionPerformed(evt);
            }
        });

        JLescola.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLescola.setForeground(new java.awt.Color(102, 0, 102));
        JLescola.setText("ID Escola:");

        JLtitulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(102, 0, 102));
        JLtitulo.setText("Gerenciamento de Doação");

        JLiddoacao.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLiddoacao.setForeground(new java.awt.Color(102, 0, 102));
        JLiddoacao.setText("ID Produto:");

        JBTconsultar.setBackground(new java.awt.Color(247, 255, 247));
        JBTconsultar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JBTconsultar.setForeground(new java.awt.Color(102, 0, 102));
        JBTconsultar.setText("Consultar");
        JBTconsultar.setName("mostrar"); // NOI18N
        JBTconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTconsultarActionPerformed(evt);
            }
        });

        JLvoluntario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLvoluntario.setForeground(new java.awt.Color(102, 0, 102));
        JLvoluntario.setText("ID Voluntário:");

        JTBdoacao.setBackground(new java.awt.Color(247, 255, 247));
        JTBdoacao.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JTBdoacao.setForeground(new java.awt.Color(102, 0, 102));
        JTBdoacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Doação", "ID Voluntário", "ID Escola", "ID Produto", "Data da Doação"
            }
        ));
        JTBdoacao.setSelectionForeground(new java.awt.Color(36, 123, 160));
        JTBdoacao.setShowGrid(true);
        jScrollPane1.setViewportView(JTBdoacao);

        JTFidproduto.setName("JTFidproduto"); // NOI18N
        JTFidproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFidprodutoActionPerformed(evt);
            }
        });

        JTFdoaano.setForeground(new java.awt.Color(102, 0, 102));
        JTFdoaano.setText("Ano");

        JLdatadoacao.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLdatadoacao.setForeground(new java.awt.Color(102, 0, 102));
        JLdatadoacao.setText("Data da doação:");

        JTFdoames.setForeground(new java.awt.Color(102, 0, 102));
        JTFdoames.setText("Mês");

        JTFdoadia.setForeground(new java.awt.Color(102, 0, 102));
        JTFdoadia.setText("Dia");

        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("French Script MT", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BonsFluidosManagement");
        jLabel4.setMinimumSize(new java.awt.Dimension(146, 50));

        JLiddoacao1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLiddoacao1.setForeground(new java.awt.Color(102, 0, 102));
        JLiddoacao1.setText("ID Doação:");

        JTFiddoacao.setName("JTFiddoacao"); // NOI18N
        JTFiddoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFiddoacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(JLtitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLdatadoacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFdoaano, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFdoames, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFdoadia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLescola)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFidescola, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JBTcadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(JBTdeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTconsultar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLvoluntario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLiddoacao, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JTFidproduto, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(JTFidvoluntario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLiddoacao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFiddoacao, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLtitulo)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFiddoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLiddoacao1))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFidproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLiddoacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLvoluntario)
                    .addComponent(JTFidvoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLescola)
                    .addComponent(JTFidescola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFdoaano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLdatadoacao)
                    .addComponent(JTFdoames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFdoadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTdeletar)
                    .addComponent(JBTcadastrar)
                    .addComponent(JBTconsultar))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        JBTcadastrar.getAccessibleContext().setAccessibleName("cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFidprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFidprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFidprodutoActionPerformed

    private void JBTcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTcadastrarActionPerformed

    private void JBTdeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTdeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTdeletarActionPerformed

    private void JBTconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTconsultarActionPerformed
      
    }//GEN-LAST:event_JBTconsultarActionPerformed

    private void JTFiddoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFiddoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFiddoacaoActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDoacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTcadastrar;
    private javax.swing.JButton JBTconsultar;
    private javax.swing.JButton JBTdeletar;
    private javax.swing.JLabel JLdatadoacao;
    private javax.swing.JLabel JLescola;
    private javax.swing.JLabel JLiddoacao;
    private javax.swing.JLabel JLiddoacao1;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JLabel JLvoluntario;
    private javax.swing.JTable JTBdoacao;
    private javax.swing.JTextField JTFdoaano;
    private javax.swing.JTextField JTFdoadia;
    private javax.swing.JTextField JTFdoames;
    private javax.swing.JTextField JTFiddoacao;
    private javax.swing.JTextField JTFidescola;
    private javax.swing.JTextField JTFidproduto;
    private javax.swing.JTextField JTFidvoluntario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
